#!/usr/bin/env python
"""Quick test to check if API returns pre-signed URLs"""
import requests
import json
import sys

BASE_URL = 'http://localhost:8000'
USERNAME = 'mobiledev'
PASSWORD = 'mobile123'  # Password from populate_mobile_dev_data.py

print("Testing API for pre-signed URLs...")
print()

# Login
print("1. Logging in...")
login_response = requests.post(
    f'{BASE_URL}/auth/login',
    json={'username': USERNAME, 'password': PASSWORD},
    timeout=5
)

if login_response.status_code != 200:
    print(f"❌ Login failed: {login_response.status_code}")
    print(login_response.text)
    sys.exit(1)

token = login_response.json()['token']
print(f"✓ Login successful")
print()

# Get items
print("2. Fetching items...")
items_response = requests.get(
    f'{BASE_URL}/items/',
    headers={'Authorization': f'Token {token}'},
    timeout=10
)

if items_response.status_code != 200:
    print(f"❌ Failed to fetch items: {items_response.status_code}")
    print(items_response.text)
    sys.exit(1)

data = items_response.json()
# Handle both list and paginated response
if isinstance(data, dict) and 'results' in data:
    items = data['results']
else:
    items = data if isinstance(data, list) else []

if not items:
    print("❌ No items found")
    sys.exit(1)

print(f"✓ Found {len(items)} items")
print()

# Check first item's image_url
print("3. Checking image URLs...")
item = items[0]
item_name = item.get('name', 'Unknown')
image_url = item.get('image_url', '')

if not image_url:
    print(f"❌ Item '{item_name}' has no image_url")
    sys.exit(1)

print(f"Item: {item_name}")
print(f"Image URL: {image_url[:200]}...")
print()

# Check if pre-signed
is_presigned = '?' in image_url and ('X-Amz-Algorithm' in image_url or 'X-Amz-Expires' in image_url or 'X-Amz' in image_url)

if is_presigned:
    print("✅ PRE-SIGNED URL DETECTED!")
    print(f"   Query params present: Yes")
    print(f"   Full URL length: {len(image_url)} chars")
    
    # Test if URL actually works
    print()
    print("4. Testing URL accessibility...")
    try:
        img_response = requests.get(image_url, timeout=10, stream=True)
        img_response.close()
        if img_response.status_code == 200:
            print("✅ URL is accessible (200 OK)")
        else:
            print(f"⚠ URL returned {img_response.status_code}")
    except Exception as e:
        print(f"⚠ Error accessing URL: {str(e)[:100]}")
else:
    print("❌ DIRECT URL (NOT PRE-SIGNED)")
    print("   Query params present: No")
    print()
    print("This means pre-signed URLs are NOT being generated by the API.")
    print("Check:")
    print("  1. USE_S3_PRESIGNED_URLS=True in .env")
    print("  2. Server was restarted after setting the env var")
    print("  3. Settings are being loaded correctly")

print()
print("="*70)

