# Generated by Django 4.2.7 on 2026-01-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_salesrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number for password reset', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['gst_no'], name='auth_app_ve_gst_no_d199ca_idx'),
        ),
    ]
