# Generated by Django 4.2.7 on 2026-01-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_vendor_gst_no_vendor_auth_app_ve_gst_no_d199ca_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='billing_mode',
            field=models.CharField(choices=[('gst', 'GST Billing'), ('non_gst', 'Non-GST Billing')], default='gst', help_text='Billing mode: GST or Non-GST', max_length=10),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['billing_mode'], name='auth_app_ve_billing_f4da57_idx'),
        ),
    ]
