# Generated by Django 4.2.7 on 2026-01-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_add_billing_mode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='auth_app_ve_billing_f4da57_idx',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='billing_mode',
        ),
    ]
