# Generated by Django 4.2.7 on 2026-01-22 01:15

import auth_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='footer_note',
            field=models.TextField(blank=True, help_text="Footer note to be displayed on bills (e.g., 'Thank you for visiting!')", null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fssai_license',
            field=models.CharField(blank=True, help_text='FSSAI License Number (required for restaurant bills)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant/Vendor logo (JPG, PNG, WebP)', null=True, upload_to=auth_app.models.vendor_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number (GSTIN) for password reset and bills', max_length=50, null=True, unique=True),
        ),
    ]
