# Generated by Django 4.2.7 on 2026-01-27 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0006_add_fssai_logo_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Vendor owner who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_memberships', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_users', to='auth_app.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'user'], name='auth_app_ve_vendor__36e8dc_idx'), models.Index(fields=['vendor', 'is_active'], name='auth_app_ve_vendor__fa42bd_idx'), models.Index(fields=['vendor', 'is_owner'], name='auth_app_ve_vendor__3a88a5_idx')],
                'unique_together': {('vendor', 'user')},
            },
        ),
    ]
