# Generated by Django 4.2.7 on 2026-01-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_vendoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='security_pin',
            field=models.CharField(blank=True, help_text='Hashed security PIN for accessing sensitive operations (user management, etc.)', max_length=128, null=True),
        ),
    ]
