# Generated by Django 4.2.7 on 2026-01-27 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_add_bill_numbering_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vendor-level CGST percentage (e.g., 2.5 for 2.5%). If set, bills automatically calculate CGST on subtotal. Leave 0 or null to use product-level GST.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vendor-level SGST percentage (e.g., 2.5 for 2.5%). If set, bills automatically calculate SGST on subtotal. Leave 0 or null to use product-level GST.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
