# Generated by Django 4.2.7 on 2026-02-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_add_vendor_cgst_sgst_percentages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cgst_percentage',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sgst_percentage',
        ),
        migrations.AddField(
            model_name='vendor',
            name='sac_code',
            field=models.CharField(blank=True, help_text='SAC (Service Accounting Code) for vendor-level GST. If set, all items use this SAC GST rate instead of their HSN codes.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sac_gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='GST percentage for SAC code (e.g., 5.00 for 5%). If SAC code is set but this is not set, default rate from mapping will be used.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
