# Generated by Django 4.2.7 on 2026-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_remove_vendor_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Custom vendor ID number for easy identification (e.g., V001, VENDOR-001). Auto-generated if not provided.', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_id'], name='auth_app_ve_vendor__4e4e26_idx'),
        ),
    ]
