# Generated by Django 4.2.7 on 2026-01-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_category_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_categor_43a476_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Items can belong to multiple categories', related_name='items', to='items.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
