# Generated by Django 4.2.7 on 2026-01-22 01:14

import django.core.validators
from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional discount amount (optional)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage (0%, 5%, 8%, 18%, or custom) - Not compulsory for item creation', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='item',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP Price (Exclusive or Inclusive based on price_type) - MANDATORY for new items', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='price_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive (GST not included in MRP)'), ('inclusive', 'Inclusive (GST included in MRP)')], default='exclusive', help_text='Exclusive: GST not included in MRP. Inclusive: GST included in MRP', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], help_text='Vegetarian or Non-Vegetarian', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Item image (JPG, PNG, WebP) - Optional. Item name shown if no image', null=True, upload_to=items.models.item_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
