# Generated by Django 4.2.7 on 2026-02-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_add_gst_pricing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gst_percentage',
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN (Harmonized System of Nomenclature) code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='GST percentage for this HSN code (e.g., 5.00 for 5%). Can override mapping defaults.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
