# Generated by Django 4.2.7 on 2026-01-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='auth_app.vendor'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='appsettings',
            unique_together={('vendor', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='appsettings',
            index=models.Index(fields=['vendor', 'device_id'], name='settings_ap_vendor__5ab70c_idx'),
        ),
    ]
