# Generated by Django 4.2.7 on 2026-01-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_appsettings_vendor_alter_appsettings_device_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appsettings',
            unique_together=set(),
        ),
    ]
