# Generated by Django 4.2.7 on 2026-01-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('settings', '0003_alter_appsettings_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appsettings',
            unique_together={('vendor', 'device_id')},
        ),
    ]
