# Generated by Django 4.2.7 on 2026-01-08 02:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_salesrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the raw material', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the raw material', null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Current stock quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Liter (L)'), ('mL', 'Milliliter (mL)'), ('pcs', 'Piece (pcs)'), ('pkt', 'Packet (pkt)'), ('box', 'Box (box)'), ('carton', 'Carton (carton)'), ('bag', 'Bag (bag)'), ('bottle', 'Bottle (bottle)'), ('can', 'Can (can)'), ('dozen', 'Dozen (dozen)'), ('m', 'Meter (m)'), ('cm', 'Centimeter (cm)'), ('sqm', 'Square Meter (sqm)'), ('cum', 'Cubic Meter (cum)')], default='kg', help_text='Unit of measurement (kg, L, pcs, etc.)', max_length=20)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (optional)', max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode (optional)', max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Supplier name', max_length=255, null=True)),
                ('supplier_contact', models.CharField(blank=True, help_text='Supplier contact', max_length=100, null=True)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, help_text='Minimum stock level (alert when below this)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Recommended reorder quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this inventory item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_restocked_at', models.DateTimeField(blank=True, help_text='Last time stock was added', null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='auth_app.vendor')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='inventory_a_vendor__d3daca_idx'), models.Index(fields=['sku'], name='inventory_a_sku_fe1a6e_idx'), models.Index(fields=['barcode'], name='inventory_a_barcode_5e1ad7_idx'), models.Index(fields=['name'], name='inventory_a_name_e937ea_idx')],
                'unique_together': {('vendor', 'name')},
            },
        ),
    ]
