# Generated by Django 4.2.7 on 2026-01-01 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_data', models.JSONField()),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['id'], name='sales_sales_id_1badf8_idx'), models.Index(fields=['device_id'], name='sales_sales_device__51fc82_idx')],
            },
        ),
    ]
