# Generated by Django 4.2.7 on 2026-01-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbackup',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_backups', to='auth_app.vendor'),
        ),
        migrations.AddIndex(
            model_name='salesbackup',
            index=models.Index(fields=['vendor', 'synced_at'], name='sales_sales_vendor__fdaad0_idx'),
        ),
    ]
