# Generated by Django 4.2.7 on 2026-01-22 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_add_fssai_logo_footer'),
        ('items', '0005_add_gst_pricing_fields'),
        ('sales', '0002_salesbackup_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, help_text='Device that created this bill', max_length=255, null=True)),
                ('invoice_number', models.CharField(help_text='Auto-generated invoice number (e.g., INV-2024-001)', max_length=100)),
                ('bill_number', models.CharField(blank=True, help_text='Bill number', max_length=100, null=True)),
                ('bill_date', models.DateField(help_text='Date of the bill')),
                ('restaurant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN for this bill', max_length=50, null=True)),
                ('fssai_license', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Logo URL for bill printing', null=True)),
                ('footer_note', models.TextField(blank=True, help_text='Footer note for bill', null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('billing_mode', models.CharField(choices=[('gst', 'GST'), ('non_gst', 'Non-GST')], default='gst', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='CGST amount (for intra-state)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='SGST amount (for intra-state)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, help_text='IGST amount (for inter-state)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID, cheque number, etc.', max_length=255, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, help_text='Change given to customer', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this bill', null=True)),
                ('table_number', models.CharField(blank=True, help_text='Table number (for restaurants)', max_length=50, null=True)),
                ('waiter_name', models.CharField(blank=True, help_text='Waiter/server name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When bill was created on mobile')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When bill was synced to server')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='auth_app.vendor')),
            ],
            options={
                'ordering': ['-synced_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='salesbackup',
            name='bill_data',
            field=models.JSONField(help_text='DEPRECATED: Use Bill model instead'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_item_id', models.UUIDField(blank=True, help_text='Original item ID from mobile (UUID string)', null=True)),
                ('item_name', models.CharField(help_text='Item name at time of sale', max_length=255)),
                ('item_description', models.TextField(blank=True, help_text='Item description at time of sale', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price at time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp_price', models.DecimalField(decimal_places=2, help_text='MRP at time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', help_text='Price type at time of sale', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity sold (supports decimals like 1.5 kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for this item (quantity * price)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, help_text='GST percentage at time of sale', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('item_gst_amount', models.DecimalField(decimal_places=2, default=0, help_text='GST amount for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('veg_nonveg', models.CharField(blank=True, choices=[('veg', 'Veg'), ('non_veg', 'Non-Veg')], help_text='Veg/Non-veg at time of sale', max_length=10, null=True)),
                ('additional_discount', models.DecimalField(decimal_places=2, default=0, help_text='Additional discount on this item', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (kg, pcs, etc.)', max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Batch number (for inventory tracking)', max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (for inventory tracking)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.bill')),
                ('item', models.ForeignKey(blank=True, help_text='Link to master Item (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='items.item')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['id'], name='sales_billi_id_039bc2_idx'), models.Index(fields=['bill', 'created_at'], name='sales_billi_bill_id_7b0593_idx'), models.Index(fields=['item'], name='sales_billi_item_id_78d43a_idx'), models.Index(fields=['original_item_id'], name='billitem_original_item_id_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['id'], name='sales_bill_id_7ff068_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['vendor', 'synced_at'], name='sales_bill_vendor__fd06cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['vendor', 'bill_date'], name='sales_bill_vendor__901df4_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['invoice_number'], name='sales_bill_invoice_4c99ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['billing_mode'], name='sales_bill_billing_e7b293_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['device_id'], name='sales_bill_device__abdbb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('vendor', 'invoice_number')},
        ),
    ]
