# Generated by Django 4.2.7 on 2026-02-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_convert_discount_to_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code at time of sale (snapshot)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='hsn_gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HSN GST percentage at time of sale (snapshot)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage at time of sale (calculated from HSN/SAC)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
